name: Checking Build
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Prepare Env
        run: |
      - run: cd . > keystore/configs.properties
      - run: cd . > keystore/easywallet.jks
      - run: echo ${{ secrets.CONFIGS }} | base64 -i --decode > keystore/configs.properties
      - run: echo ${{ secrets.JKS_SIGNER }} | base64 -i --decode > keystore/easywallet.jks
      - run: echo ${{ secrets.GIT_TOKEN }} | base64 -i --decode >> local.properties

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle Build
        run: ./gradlew build
